use master;

--Restore DB
go
Create Procedure ImDB
AS
Begin
	ALTER DATABASE STORES_CHAIN
	SET SINGLE_USER
	WITH ROLLBACK IMMEDIATE;

	RESTORE DATABASE STORES_CHAIN
		FROM disk = 'D:\Subject\BD_COURSE\backups\STORES_CHAIN.bak'
			WITH replace;
	ALTER DATABASE STORES_CHAIN
	SET MULTI_USER;
End;