use STORES_CHAIN;

--for employees
CREATE UNIQUE NONCLUSTERED INDEX indx_Empl ON Employees(Name_First, Name_Sec);

--for products order
CREATE UNIQUE NONCLUSTERED INDEX indx_ProdNum ON PRODUCTS(Prod_Num);
CREATE UNIQUE NONCLUSTERED INDEX indx_ProdNam ON PRODUCTS(Prod_Name);
CREATE UNIQUE NONCLUSTERED INDEX indx_ProdBar ON PRODUCTS(Prod_Id);
CREATE NONCLUSTERED INDEX indx_ProdPP ON PRODUCTS(Price_Purchase);
CREATE NONCLUSTERED INDEX indx_ProdPS ON PRODUCTS(Price_Sell);
CREATE NONCLUSTERED INDEX indx_ProdWei ON PRODUCTS(Weight);
CREATE NONCLUSTERED INDEX indx_ProdVol ON PRODUCTS(Volume);
CREATE UNIQUE NONCLUSTERED INDEX indx_ProdNumD ON PRODUCTS(Prod_Num DESC);
CREATE UNIQUE NONCLUSTERED INDEX indx_ProdNamD ON PRODUCTS(Prod_Name DESC);
CREATE UNIQUE NONCLUSTERED INDEX indx_ProdBarD ON PRODUCTS(Prod_Id DESC);
CREATE NONCLUSTERED INDEX indx_ProdPPD ON PRODUCTS(Price_Purchase DESC);
CREATE NONCLUSTERED INDEX indx_ProdPSD ON PRODUCTS(Price_Sell DESC);
CREATE NONCLUSTERED INDEX indx_ProdWeiD ON PRODUCTS(Weight DESC);
CREATE NONCLUSTERED INDEX indx_ProdVolD ON PRODUCTS(Volume DESC);

--for users(buyers)
CREATE UNIQUE NONCLUSTERED INDEX indx_User ON USERS(Id_User DESC);

--for stores
CREATE UNIQUE NONCLUSTERED INDEX indx_StorI ON STORES(Id_Store);
CREATE UNIQUE NONCLUSTERED INDEX indx_StorIDesc ON STORES(Id_Store DESC);
CREATE UNIQUE NONCLUSTERED INDEX indx_Stor ON STORES(Name_Store, County);

--for basket 
CREATE UNIQUE NONCLUSTERED INDEX indx_Bask ON USER_BASKET(Id_Item, Product, Id_User);
CREATE UNIQUE NONCLUSTERED INDEX indx_Bask ON USER_BASKET(Id_User);

--for admin
CREATE UNIQUE NONCLUSTERED INDEX indx_Bask ON STORE_ADMIN(Admin_Login);
CREATE UNIQUE NONCLUSTERED INDEX indx_Bask ON STORE_ADMIN(Admin_Pass);
CREATE UNIQUE NONCLUSTERED INDEX indx_Bask ON STORE_ADMIN(Admin_Login,Admin_Pass);